stages:
    - pull-wordpress-svn
    - move-to-svn
    - deploy

cache:
    untracked: true
    key: ${CI_COMMIT_REF_SLUG}
    paths:
        - sender-net-automated-emails

pull-wordpress-svn:
    stage: pull-wordpress-svn
    script: 
        - svn co https://plugins.svn.wordpress.org/sender-net-automated-emails

move-to-svn:
    stage: move-to-svn
    script:
        - rsync -a --exclude .git --exclude .idea --exclude 'sender-net-automated-emails' . sender-net-automated-emails/trunk/


deploy:
    stage: deploy
    script: #todo deploy to 
        - cd sender-net-automated-emails
        - svn add --force trunk/*
        - ls -la
        - svn ci -m 'Minor update'
